baseurl = "http://pionjar.se"
languageCode = "sv-SE"
title = "Pionjärerna"

[params]
onlyLogotype = true
tagline = "Alltid redo för goda gärningar"
logotype = "logotype_sv.svg"
footer = "copyright &copy; 2014 Pionjärerna"
